name: App Main Orquestrador

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite rodar manualmente no GitHub

jobs:
  # 1. Chama o workflow no repo-nested
  build:
    name: develop
    uses: joaobcandido/repo-nested/.github/workflows/passos.yml@main
    with:
      ambiente: 'Produção'

 
